# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a9d5c94434483c7080b380706878fd05bebf42d71c86988fb9c6d312e63f5163d3c1b6694f61aa9937257b5387079aaa5758fbbb3bcd69f432b9e8aee7c8d5d5

test:
  secret_key_base: 2a10ed0aa5e27cedbfb870929852a1e550d63004266bea59da89168dc11c36d7e351ea80fa180bf9c222a4177e777bcad45675c941a9793fd327c84e2b4c964e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
